---
- hosts: all
  become: true
  become_method: sudo

  vars:
    required_packages:
    - git
    - tcptraceroute
    - nmap
    - jq
    - python3-pip
    required_python_packages: []
    golang_version: '1.11'
    golang_gopath: go
    golang_additional_libraries:
    - golang.org/x/tools/cmd/goimports
    golang_users:
    - root
    - vagrant

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists
  - name: exclude beats
    set_fact:
      elasticsearch_install_auditbeat: False
      elasticsearch_install_heartbeat: False

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.golang
  - default_tasks
  - andrelohmann.beats
  - beats_patch
  - unbound_tasks
  - unbound_tests
  - unbound_exporter


...
