---

- name: install unbound
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - libfstrm0
    - libprotobuf-c1
    - xz-utils

# as of unbound is listening on 0.0.0.0, we need to disable systemd-resolved
- name: stop systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: stopped
    enabled: no

# dpkg -i libunbound8_1.9.6-al1_amd64.deb unbound-anchor_1.9.6-al1_amd64.deb unbound_1.9.6-al1_amd64.deb
- name: install the compiled unbound packages
  apt:
    deb: "{{ item }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - /root/unbound_package/libunbound8_1.9.6-al1_amd64.deb
  - /root/unbound_package/unbound-anchor_1.9.6-al1_amd64.deb
  - /root/unbound_package/unbound_1.9.6-al1_amd64.deb

# touch log file
- name: Create an insecure log file
  file:
    path: /var/log/unbound.log
    state: touch
    owner: unbound
    group: unbound
    mode: '0644'

# Note: You can check config using unbound-checkconf
- name: configure unbound (unbound.conf)
  copy:
    dest: /etc/unbound/unbound.conf
    content: |
      server:
        #chroot: ""
        access-control: 127.0.0.0/8 allow
        access-control: 0.0.0.0/0 allow
        verbosity: 3
        logfile: /var/log/unbound.log
        log-queries: yes
        extended-statistics: yes
        # listen on public
        interface: 0.0.0.0
        interface-automatic: yes
      forward-zone:
        name: "."
        forward-addr: 1.0.0.1@53#one.one.one.one
        forward-addr: 1.1.1.1@53#one.one.one.one
        forward-addr: 8.8.4.4@53#dns.google
        forward-addr: 8.8.8.8@53#dns.google
        forward-addr: 9.9.9.9@53#dns.quad9.net
        forward-addr: 149.112.112.112@53#dns.quad9.net
      remote-control:
        control-enable: yes
    owner: root
    group: root
    mode: '0644'

- name: configure unbound logrotate
  copy:
    dest: /etc/logrotate.d/unbound
    content: |
      /var/log/unbound.log {
        daily
        rotate 3
        maxsize 1G
        missingok
        notifempty
        compress
        sharedscripts
        create 644 unbound unbound
        postrotate
        # /usr/sbin/unbound-control log_reopen
        systemctl restart unbound
        endscript
      }

- name: allow unbound.log read-write in apparmor
  lineinfile:
    path: /etc/apparmor.d/local/usr.sbin.unbound
    regexp: "^/var/log/unbound.log rw,"
    line: "/var/log/unbound.log rw,"

- name: reload apparmor config
  shell: apparmor_parser -r /etc/apparmor.d/usr.sbin.unbound
  args:
    executable: /bin/bash

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: restart unbound
  systemd:
    name: "unbound"
    state: restarted
    enabled: yes

- name: enable logshipping in filebeat yaml
  lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: "^  enabled:"
    line: "  enabled: true"
    insertafter: '^  # Change to true to enable this input configuration.'

- name: restart filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted

...
