---

- name: copy dockerfile
  copy:
    src: Dockerfile
    dest: /root/Dockerfile
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Build the image
  docker_image:
    build:
      path: /root
    name: unbound_exporter
    source: build

- name: extract unbound_exporter from image
  shell: docker run --rm --entrypoint /bin/sh unbound_exporter -c "cat /go/bin/unbound_exporter" > /root/unbound_exporter
  args:
    executable: /bin/bash

- name: copy unbound exporter to /usr/local/bin
  copy:
    src: /root/unbound_exporter
    dest: /usr/local/bin/unbound_exporter
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: add unbound_exporter systemd unit file
  copy:
    src: unitfile
    dest: /etc/systemd/system/unbound_exporter.service
    mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable unbound_exporter
  systemd:
    name: unbound_exporter
    enabled: yes

- name: start unbound_exporter
  systemd:
    name: unbound_exporter
    state: started

- name: add prometheus metricbeat module
  copy:
    src: prometheus.yml
    dest: /etc/metricbeat/modules.d/prometheus.yml
    mode: 0644

- name: restart metricbeat
  systemd:
    name: metricbeat
    state: restarted


...
